name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/liveChat
          git pull origin main
          cd client
          npm install
          npm run build
          sudo cp -r build/* /var/www/html/
          # Restart backend if needed, e.g.:
          # pm2 restart server.js
          sudo systemctl reload nginx
